### PR TITLE
Fix stats panel ascending

### PR DESCRIPTION
**Pull request by lukebrody**
Will merge this once #321 lands

### CODE REVIEW

**Comment by kavigupta** [comment]
We should add a test to prevent a regression

**Comment by lukebrody** [comment]
> We should add a test to prevent a regression; ideally assertion based not image based

@kavigupta Added!

**Comment by lukebrody** [comment]
Need to add a lint check for test.only!!!

**Review by kavigupta — APPROVED** [review]
LGTM

**Pull request merged**
