### PR TITLE
add check that all settings are either included in the settings vector or explicitly listed as not included

### PR DESCRIPTION
**Pull request by kavigupta**

### CODE REVIEW

**Comment by lukebrody** [comment]
LGTM

**Comment by lukebrody** [comment]
Wait hold up, what happens if I have a setting in `NotIncludedInSettingsVector` that's actually in the settings vector

**Comment by kavigupta** [comment]
Is there a way to do a type level check for that?

**Comment by lukebrody** [comment]
> Is there a way to do a type level check for that?

https://www.typescriptlang.org/play/?#code/C4TwDgpgBAcg9sAQggFgZWAJwJYDsDmAgrgCYwCuAtgEYSYA8AKgHxQC8UAzlnvlAD5RcVWpigQAHsAilOURlAD8UAGYBDADadoALihZyEAFAmNEYFDV74SVBhwFiZEXXrcH+ZkbMXq1hMjA6DyOpBQ0rsIRmF4+UADG-rZB9rxO4aJuIXyCUaJeQA

**Comment by kavigupta** [comment]
Lol this type system is so weirdly advanced and so dumb at the same time

**Comment by kavigupta** [comment]
dependent types for my goddamn javascript webapp

**Pull request merged**
