### PR TITLE
fix the discord links issue by just getting rid of % in links

### PR DESCRIPTION
**Pull request by kavigupta**
Resolves https://github.com/kavigupta/urbanstats/issues/506

### CODE REVIEW

**Comment by lukebrody** [comment]
Won't this break some existing links? Also we should remove the existing patch probably?

**Comment by lukebrody** [comment]
> Won't this break some existing links?

Nevermind I see we go the other way

**Comment by kavigupta** [comment]
Yeah and the existing fix doesn't like, cause issues. We can remove it if we like

**Comment by lukebrody** [comment]
> Yeah and the existing fix doesn't like, cause issues. We can remove it if we like

I guess it might break some links that are working if we remove it...

**Comment by lukebrody** [comment]
might have been good to leave some comments around 😅

**Pull request merged**
